// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0avMiuyFGkHGH5y8VXQU-NsylPdGi1Zc',
    appId: '1:90532665779:web:57fb8951b6118e058013c6',
    messagingSenderId: '90532665779',
    projectId: 'havapaw-11e23',
    authDomain: 'havapaw-11e23.firebaseapp.com',
    storageBucket: 'havapaw-11e23.firebasestorage.app',
    measurementId: 'G-87PJY4ZN8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbSg4IpePxsttJGygiTM7S5hkBOvrazz0',
    appId: '1:90532665779:android:dd26becfdb80946b8013c6',
    messagingSenderId: '90532665779',
    projectId: 'havapaw-11e23',
    storageBucket: 'havapaw-11e23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqUii7r0LstYE6rMvyNWD3QubnfXp6e7U',
    appId: '1:90532665779:ios:6843099e654f5f648013c6',
    messagingSenderId: '90532665779',
    projectId: 'havapaw-11e23',
    storageBucket: 'havapaw-11e23.firebasestorage.app',
    iosBundleId: 'com.example.havapaw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqUii7r0LstYE6rMvyNWD3QubnfXp6e7U',
    appId: '1:90532665779:ios:6843099e654f5f648013c6',
    messagingSenderId: '90532665779',
    projectId: 'havapaw-11e23',
    storageBucket: 'havapaw-11e23.firebasestorage.app',
    iosBundleId: 'com.example.havapaw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0avMiuyFGkHGH5y8VXQU-NsylPdGi1Zc',
    appId: '1:90532665779:web:5df5c2ca7906d7448013c6',
    messagingSenderId: '90532665779',
    projectId: 'havapaw-11e23',
    authDomain: 'havapaw-11e23.firebaseapp.com',
    storageBucket: 'havapaw-11e23.firebasestorage.app',
    measurementId: 'G-YCHJMNF5RW',
  );
}
